### PR TITLE
Separate building play_routes to a helper to allow remote builds

### LINKED ISSUE #38: Impossible to utilize play_routes rules in remote builds
Due to bazelbuild/bazel#6393 and the fact that implementation uses `ctx.actions.declare_directory`, contents of which are not transferred to remote machine, it's impossible to build `play_routes` targets remotely. Attempting to do so results in:

```
INFO: From Bundling compiled play routes into srcjar:
find: ‘bazel-out/k8-fastbuild/bin/server/play/routes/server_routes_file’: No such file or directory
ERROR: /home/circleci/grabl/server/BUILD:39:14: scala //server:server-routes-lib failed (Exit 1)
ChUI4/gCEOnPAhjsrPUCIKMuYJcFaAESFAgnELnJgSIY3Y4sIAwoklAwgOAD
java.lang.RuntimeException: Must have input files from either source jars or local files.
	at io.bazel.rulesscala.scalac.ScalacProcessor.processRequest(ScalacProcessor.java:68)
	at io.bazel.rulesscala.worker.GenericWorker.run(GenericWorker.java:114)
	at io.bazel.rulesscala.scalac.ScalaCInvoker.main(ScalaCInvoker.java:41)
```

(that's with `//server:server-routes-lib` (`scala_library`) depending on `//server:server-routes-lib` (`play_routes`))

### PR DESCRIPTION
**Pull request by vmax**
Fix #38 
Two actions (executing routes compiler and then combining them with zipper) are collapsed into one, which allows for remote building

### CODE REVIEW

File: play-routes/play-routes-helper.sh [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+set -e
+
+OUTPUT_DIR=$(mktemp -d)
+
+PREFIX=$1
+shift
+OUTPUT_SRCJAR=$1
+shift
+ZIPPER_PATH=$1
+shift
```
Comment (DavidANeil) [inline play-routes/play-routes-helper.sh]: I think this would be easier as 
```suggestion
PREFIX=$1
OUTPUT_SRCJAR=$2
ZIPPER_PATH=$3
shift 3
```

**Review by DavidANeil — APPROVED** [review]

File: play-routes/play-routes-helper.sh (hunk 1 above)
Comment (vmax) [reply play-routes/play-routes-helper.sh]: @DavidANeil thanks, that looks cleaner!

**Review by DavidANeil — APPROVED** [review]

**Comment by pauldraper** [comment]
Is this because remote builds can't work with directories...?

Honestly, the whole zip/unzip stuff is really a pain. It would be nice if rules_scala and everything else supported directories.

**Comment by vmax** [comment]
@pauldraper yeah, the relevant issue (of not supporting directories in remote builds) is bazelbuild/bazel#6393

**Comment by pauldraper** [comment]
@vmax I thought that issue was simply that declare_directory didn't create the directory for remote builds (unlike local builds).

And that tool could just create the dir themselves.

**Comment by SrodriguezO** [comment]
@vmax have you verified that this change fixes the issue you observed in #38?

**Comment by vmax** [comment]
@SrodriguezO yes, we at @graknlabs are using our forked version extensively for ~2 weeks

**Comment by SrodriguezO** [comment]
@vmax thanks for the update. We'll merge this :)
